# Generated by Django 3.0.5 on 2021-04-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Product',
        ),
    ]
